export const copy = {
  appTitle: "生活记忆助手",
  conversation: {
    inputLabel: "想说的话",
    placeholder: "说一句话，我来判断是记住，还是帮你找。",
    voiceAction: "语音输入",
    listening: "我在听，你慢慢说",
    send: "发送给记忆助手",
    thinking: "正在理解你说的话",
  },
  recall: {
    recordedEvidence: "你之前记录过",
    contextLinkEvidence: "可能相关",
    graphitiEvidence: "长期记忆里有相关线索",
    noEvidenceBody: "我没有找到你之前说过这件事。",
    correct: "这不对，改一下",
    correctionLabel: "哪里不对？",
    correctionPlaceholder: "例如：不是青菜，是菠菜。",
    sendCorrection: "提交修改",
    appliedTag: "已更新",
    appliedNote: "这次先按你的修改显示。",
    originalAnswerLabel: "之前的说法",
  },
  events: {
    refresh: "刷新",
  },
  tasks: {
    title: "事项",
    emptyTitle: "还没有待处理事项",
    emptyBody: "说一句话后，我会把需要处理的事放到这里。",
    urgent: "紧急",
    needsConfirmation: "待我确认",
    todayReminder: "今天提醒",
    confirmedReminder: "确认",
    latestAnswer: "最近回答",
    draft: "文字草稿",
    organizing: "正在整理提醒",
    remembered: "已记住",
    organizeFailed: "已保存原文，整理失败",
    retry: "再试一次",
    dismissDraft: "删除",
  },
  reminders: {
    confirm: "确认提醒",
    quickTimes: {
      morning: "早上 7 点",
      noon: "中午 12 点",
      evening: "晚上 7 点",
    },
  },
  status: {
    refreshed: "已刷新。",
    reminderConfirmed: "提醒已确认。",
    feedbackSaved: "我记下这个修改了。",
    turnCompleted: "处理好了。",
    profileSaved: "设置已保存。",
  },
  examples: {
    hint: "试试这样跟我说：",
    items: [
      "明天下午 3 点要去复查",
      "医保卡放在抽屉左边",
      "上次把钥匙放哪了",
    ],
  },
  settings: {
    open: "设置",
    close: "收起",
    title: "我的设置",
    textScaleLabel: "字号",
    textScaleNormal: "标准",
    textScaleXl: "大",
    profileSection: "我的画像",
    fieldDisplayName: "称呼",
    fieldDisplayNamePlaceholder: "比如：王奶奶",
    fieldWakeTime: "一般几点起床",
    fieldSleepTime: "一般几点睡觉",
    fieldMedications: "正在吃的药（每行一种，名称在前）",
    fieldMedicationsPlaceholder: "降压药 苯磺酸氨氯地平 早餐后一片",
    fieldPlaces: "常去的地方（每行一个）",
    fieldPlacesPlaceholder: "社区医院\n小区超市",
    fieldNotes: "想让我记住的其他事",
    fieldNotesPlaceholder: "比如：右耳听不太清",
    save: "保存",
    saveSuccess: "已更新",
  },
  snapshot: {
    title: "今天先帮你看一眼",
    todayPrefix: "今天有",
    todaySuffix: "件事要做",
    yesterdayLabel: "昨天确认了：",
    weekLabel: "这周你常说到：",
    emptyToday: "今天还没排上事",
    emptyYesterday: "昨天没有确认事项",
    emptyWeek: "这周还在记新事",
    dismiss: "今天就先这样",
  },
  eventTypes: {
    health: "健康",
    medication: "用药",
    appointment: "复查",
    family: "家人",
    shopping: "购物",
    finance: "财务",
    place: "地点",
    object: "物品",
    general: "日常",
  },
  draft: {
    rememberedTag: "已记住",
  },
} as const;
