export const copy = {
  appTitle: "生活记忆助手",
  conversation: {
    inputLabel: "想说的话",
    placeholder: "说一句话，我来判断是记住，还是帮你找。",
    voiceAction: "语音输入",
    listening: "我在听，你慢慢说",
    send: "发送给记忆助手",
    thinking: "正在理解你说的话",
  },
  recall: {
    recordedEvidence: "你之前记录过",
    contextLinkEvidence: "可能相关",
    graphitiEvidence: "长期记忆里有相关线索",
    noEvidenceBody: "我没有找到你之前说过这件事。",
    correct: "这不对，改一下",
    correctionLabel: "哪里不对？",
    correctionPlaceholder: "例如：不是青菜，是菠菜。",
    sendCorrection: "提交修改",
  },
  events: {
    refresh: "刷新",
  },
  tasks: {
    title: "事项",
    emptyTitle: "还没有待处理事项",
    emptyBody: "说一句话后，我会把需要处理的事放到这里。",
    urgent: "紧急",
    needsConfirmation: "待我确认",
    todayReminder: "今天提醒",
    confirmedReminder: "确认",
    latestAnswer: "最近回答",
    draft: "文字草稿",
    organizing: "正在整理提醒",
    remembered: "已记住",
    organizeFailed: "已保存原文，整理失败",
  },
  reminders: {
    confirm: "确认提醒",
    quickTimes: {
      morning: "早上 7 点",
      noon: "中午 12 点",
      evening: "晚上 7 点",
    },
  },
  status: {
    refreshed: "已刷新。",
    reminderConfirmed: "提醒已确认。",
    feedbackSaved: "我记下这个修改了。",
    turnCompleted: "处理好了。",
  },
} as const;
